Use encore contracts
heimrichhannot/contao-tiny-slider-bundle pull request #11
Opened 2022-10-20 08:41 UTC by salteax

This PR adds support for encore contracts.

2022-11-01 08:25 UTC, koertho requested changes
Sieht gut aus, habe noch ein paar Fehler angemerkt :)

2022-11-01 08:25 UTC, koertho commented on src/Asset/EncoreExtension.php
> +            EncoreEntry::create('contao-tiny-slider-bundle', 'src/Resources/assets/js/contao-tiny-slider-bundle-theme.js')
C&P-Fehler ;)

2022-11-01 08:25 UTC, koertho commented on src/Asset/FrontendAssets.php
> +        $this->addPageEntrypoint('contao-tiny-slider-bundle', [
Hier fehlt noch das Theme?

2023-04-03 08:43 UTC, salteax commented
@koertho

2023-04-03 14:53 UTC, koertho requested changes

2023-04-03 14:53 UTC, koertho commented on src/Asset/EncoreExtension.php
> +        ];
Hier fehlt noch der Theme-Entry: contao-tiny-slider-bundle-theme

2023-04-26 11:19 UTC, salteax commented
@koertho passt das jetzt?

2023-04-26 11:50 UTC, koertho approved these changes
Sieht gut aus. Hast du es mal kurz getestet?

2023-05-08 13:31 UTC, salteax commented
@koertho habe noch ein paar Fehler gefunden und berichtigt, jetzt läuft es aber.

2023-05-22 06:58 UTC, koertho approved these changes

2023-05-22 06:59 UTC, koertho commented
Gerne als neue Minor-Version taggen, bitte Changelog und Readme anpassen :)

2023-05-22 12:34 UTC, merged